version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
