# Generated by Django 5.1.2 on 2025-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('docx', 'DOCX to PDF'), ('xlsx', 'Excel to PDF'), ('pptx', 'PowerPoint to PDF'), ('image', 'Image to PDF'), ('merge', 'Merge PDFs'), ('compress', 'Compress PDF'), ('split', 'Split PDF'), ('rotate', 'Rotate PDF')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_free_operation', models.BooleanField(default=False)),
                ('free_limit', models.IntegerField(default=0, help_text='Number of free conversions for new users')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conversion Pricing',
                'verbose_name_plural': 'Conversion Pricing',
                'ordering': ['operation_type'],
            },
        ),
    ]
