# Generated by Django 5.1.2 on 2025-09-07 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_conversionpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('conversion', 'Conversion'), ('balance_add', 'Balance Added'), ('refund', 'Refund')], max_length=20)),
                ('operation_type', models.CharField(blank=True, choices=[('docx', 'DOCX to PDF'), ('xlsx', 'Excel to PDF'), ('pptx', 'PowerPoint to PDF'), ('image', 'Image to PDF'), ('merge', 'Merge PDFs'), ('compress', 'Compress PDF'), ('split', 'Split PDF'), ('rotate', 'Rotate PDF')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in EUR', max_digits=10)),
                ('payment_method', models.CharField(choices=[('free_conversion', 'Free Conversion'), ('balance', 'Balance Deduction'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=20)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_conversions_before', models.IntegerField(default=0)),
                ('free_conversions_after', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='document.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
