# Generated by Django 5.1.2 on 2025-09-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionpricing',
            name='price',
        ),
        migrations.AddField(
            model_name='conversionpricing',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Base price per file', max_digits=5),
        ),
        migrations.AddField(
            model_name='conversionpricing',
            name='free_pages',
            field=models.IntegerField(default=0, help_text='Number of pages included in base price'),
        ),
        migrations.AddField(
            model_name='conversionpricing',
            name='max_price_per_file',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum price cap per file (0 = no cap)', max_digits=5),
        ),
        migrations.AddField(
            model_name='conversionpricing',
            name='minimum_charge',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Minimum charge per operation', max_digits=5),
        ),
        migrations.AddField(
            model_name='conversionpricing',
            name='price_per_page',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost per page', max_digits=5),
        ),
        migrations.AddField(
            model_name='conversionpricing',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price per File'), ('per_page', 'Per Page'), ('file_plus_pages', 'Base Price + Per Page')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversionpricing',
            name='operation_type',
            field=models.CharField(choices=[('docx_to_pdf', 'DOCX to PDF'), ('pdf_to_docx', 'PDF to DOCX'), ('xlsx', 'Excel to PDF'), ('pptx', 'PowerPoint to PDF'), ('image', 'Image to PDF'), ('merge', 'Merge PDFs'), ('compress', 'Compress PDF'), ('split', 'Split PDF'), ('rotate', 'Rotate PDF'), ('watermark', 'Add Watermark'), ('encrypt', 'Encrypt PDF'), ('extract', 'Extract Pages'), ('ocr', 'OCR Recognition')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('docx_to_pdf', 'DOCX to PDF'), ('pdf_to_docx', 'PDF to DOCX'), ('xlsx', 'Excel to PDF'), ('pptx', 'PowerPoint to PDF'), ('image', 'Image to PDF'), ('merge', 'Merge PDFs'), ('compress', 'Compress PDF'), ('split', 'Split PDF'), ('rotate', 'Rotate PDF'), ('watermark', 'Add Watermark'), ('encrypt', 'Encrypt PDF'), ('extract', 'Extract Pages'), ('ocr', 'OCR Recognition')], max_length=20, null=True),
        ),
    ]
